=== willianmk/Magento-config-XSD/xsd/theme_layout_local.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://www.w3schools.com"
xmlns="http://www.w3schools.com"
elementFormDefault="qualified">
    <xs:element name="layout">
        <xs:annotation>
            <xs:documentation>
                This is the layout configuration root node
            </xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element name="default">
                    <xs:annotation>
                        <xs:documentation>
                            Default node for layout configuration
                        </xs:documentation>
                    </xs:annotation>
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="remove">
                                <xs:annotation>
                                    <xs:documentation>
                                        Tag for removing layout reference
                                    </xs:documentation>
                                </xs:annotation>
                                <xs:complexType>
                                    <xs:attribute name="name" type="xs:string">
                                        <xs:annotation>
                                            <xs:documentation>
                                                Reference name to be removed
                                            </xs:documentation>
                                        </xs:annotation>
                                    </xs:attribute>
                                </xs:complexType>
                            </xs:element>
                            
                            <xs:element name="reference" type="reference">
                                <xs:annotation>
                                    <xs:documentation>
                                        Reference tag to be added
                                    </xs:documentation>
                                </xs:annotation>
                            </xs:element>
                            
                            <xs:element name="block">
                                <xs:complexType>
                                    <xs:complexContent>
                                        <xs:extension base="reference">
                                            <xs:attribute name="type"></xs:attribute>
                                            <xs:attribute name="as"></xs:attribute>
                                        </xs:extension>
                                    </xs:complexContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>          
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:complexType name="reference">
        <xs:attribute name="name">
            <xs:annotation>
                <xs:documentation>
                        Reference name to be added
                </xs:documentation>
            </xs:annotation>
        </xs:attribute>
                                    
        <xs:sequence>
            <xs:element name="action">
                <xs:annotation>
                    <xs:documentation>
                        Action name to be executed when the reference is called
                    </xs:documentation>
                </xs:annotation>
                                            
                <xs:complexType>
                    <xs:attribute name="method" type="xs:string"></xs:attribute>
                                                
                    <xs:all>
                        <xs:element name="stylesheet" type="xs:string">
                            <xs:annotation>
                                <xs:documentation>
                                    Path for the stylesheet file
                                </xs:documentation>
                            </xs:annotation>
                        </xs:element>
                                                    
                        <xs:element name="template" type="xs:string">
                            <xs:annotation>
                                <xs:documentation>
                                    Template path for the action call
                                </xs:documentation>
                            </xs:annotation>
                        </xs:element>
                                                    
                        <xs:element name="applied">
                            <xs:annotation>
                                <xs:documentation>
                                    Tag indicating whether the action is applied. This parameter accepts 0 false and 1 for true.
                                </xs:documentation>
                            </xs:annotation>
                            <xs:simpleType>
                                <xs:restriction base="xs:integer">
                                    <xs:pattern value="[0-1]"></xs:pattern>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                    </xs:all>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== willianmk/Magento-config-XSD/xml/theme_layout_local.xml
<?xml version="1.0" encoding="UTF-8"?>
<layout xmlns="http://magento.com/schema/theme/layout"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation=" ../xsd/theme_layout_local.xsd">
    <default>
        <remove name="right.poll"></remove>
        
        <reference name="referencia">
            <action method="index">
                <applied></applied>
            </action>
        </reference>
        
        <block name="name" type="type" as="alias">
            <action method="method">
                <applied>1</applied>
                <stylesheet>stylesheets</stylesheet>
                <template></template>
            </action>
        </block>
    </default>
</layout>
